pipeline {
    agent {
        docker {
            image 'jenkins/jenkins:lts'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_REGION = 'eu-north-1'
        DOCKER_IMAGE_FRONTEND = 'dilukshaupeka/todo-frontend'
        DOCKER_IMAGE_AUTH_SERVICE = 'dilukshaupeka/todo-auth'
        DOCKER_IMAGE_MONGODB = 'dilukshaupeka/todo-mongodb'
        TERRAFORM_CONTAINER = 'terraform'
        ANSIBLE_CONTAINER = 'ansible'
        APP_ENV = 'production'
        MONGODB_ATLAS_URI = credentials('MONGODB_ATLAS_URI')
        JWT_SECRET = credentials('JWT_SECRET')
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Diluksha-Upeka/To-do.git'
            }
        }
        stage('Terraform Apply') {
            steps {
                script {
                    sh '''
                    docker exec $TERRAFORM_CONTAINER terraform init
                    docker exec $TERRAFORM_CONTAINER terraform apply -auto-approve
                    '''
                }
            }
        }
        stage('Ansible Configuration') {
            steps {
                script {
                    sh '''
                    docker exec $ANSIBLE_CONTAINER ansible-playbook -i inventory/aws_ec2.ini playbook.yml
                    '''
                }
            }
        }
        stage('Docker Build and Push') {
            steps {
                script {
                    sh '''
                    docker login -u dilukshaupeka -p $DOCKERHUB_TOKEN
                    docker build -t $DOCKER_IMAGE_FRONTEND ./frontend
                    docker build -t $DOCKER_IMAGE_AUTH_SERVICE ./auth-service
                    docker build -t $DOCKER_IMAGE_MONGODB ./mongodb
                    docker push $DOCKER_IMAGE_FRONTEND
                    docker push $DOCKER_IMAGE_AUTH_SERVICE
                    docker push $DOCKER_IMAGE_MONGODB
                    '''
                }
            }
        }
        stage('Deploy to AWS') {
            steps {
                script {
                    sh '''
                    docker exec $ANSIBLE_CONTAINER ansible-playbook -i inventory/aws_ec2.ini deploy.yml
                    '''
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
} 